### ISSUE TITLE
Teste envio de evento.

### ISSUE THREAD

**Issue by eltonfernando** [moluskorp/ticonsulte-documentacao#1]
Realizei uma tentativa de envio de evento usando o seguinte script
```python
import requests
from datetime import datetime
endpoint = "https://ticonsulte.onrender.com"

def get_session():
    data ={
    "username": "18919379000142",
    "password": "18919379000142"
    }
    result = requests.post(endpoint + "/sessions", json=data)
    return result.json()

result = get_session()
token = result["token"]
data_time = str(datetime.now()).replace(" ", "T")
event = {"token": token,
         "rule_name": "Exit",
         "event_time": data_time,
         "channel_name": "Camera_test"}

print(event)
result = requests.post(endpoint + "/visitor/cam", json=event)
print(result)
print(result.text)
print(result.json())
```

meu primeiro teste 

{'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWduIjp7InN1YiI6IjUxMDFkNTNhLTJhNTMtNDc0Yy05MWE5LWE1NWIzZTllZTNmOSIsIm9mZmljZSI6Ijk1ODAyYTAzLWI5NWYtNGNmMS1hMzIyLWEwNTQ2OTdhMjU5MSJ9LCJpYXQiOjE3MTc0NTY5NjgsImV4cCI6MTcxNzU0MzM2OH0.zvNe7plgwyHNc4o0V6FzN5fdOaRkmroVJOnVfhIvSvU', 'rule_name': 'Exit', 'event_time': '2024-06-03T20:22:48.805636', 'channel_name': 'Camera_test'}
<Response [400]>
{"message":"Validation error.","issues":{"_errors":[],"camera":{"_errors":["Required"]}}}

adcionei o parametro "camera" no arquivo de envio e revebi 
<Response [500]>
{"message":"Internal server error"}

não sei o que estou fazendo de errado

**Comment by eltonfernando** [comment]
Tentando com 
```python
import requests
from datetime import datetime
endpoint = "https://ticonsulte.onrender.com"

def get_session():
    data ={
    "username": "18919379000142",
    "password": "18919379000142"
    }
    result = requests.post(endpoint + "/sessions", json=data)
    return result.json()

result = get_session()
token = result["token"]
data_time = datetime.now().isoformat()
event = {"token": token,
         "rule_name": "Exit",
         "event_time": data_time,
         "channel_name": "Camera_test",
         "camera": "Camera_test"}

print(event)
result = requests.post(endpoint + "/visitor", json=event)
print(result)
print(result.text)
print(result.json())

```

recebo

{'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWduIjp7InN1YiI6IjUxMDFkNTNhLTJhNTMtNDc0Yy05MWE5LWE1NWIzZTllZTNmOSIsIm9mZmljZSI6Ijk1ODAyYTAzLWI5NWYtNGNmMS1hMzIyLWEwNTQ2OTdhMjU5MSJ9LCJpYXQiOjE3MTc0NTg2MzQsImV4cCI6MTcxNzU0NTAzNH0.ggASIWmBSB4ShUNZUz1QnFi0IyL2Rd5eyxs2YZrlcTw', 'rule_name': 'Exit', 'event_time': '2024-06-03T20:50:34.243905', 'channel_name': 'Camera_test', 'camera': 'Camera_test'}
<Response [400]>
{"message":"Validation error.","issues":{"_errors":[],"event_time":{"_errors":["Expected date, received string"]}}}

**Comment by moluskorp** [comment]
Oi Elton , a rota da aplicação estava errada na documentação , a rota correta é somente /visitor, a /visitor/cam era pra uso interno aqui , por isso que deu problema.. Ja acertei a rota na documentação !

**Comment by moluskorp** [comment]
Oi Elton , a rota da aplicação estava errada na documentação , a rota correta é somente /visitor, a /visitor/cam era pra uso interno aqui , por isso que deu problema.. Ja acertei a rota na documentação !
